steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/umlops/gcr-umlops/bank-campaign-model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/umlops/gcr-umlops/bank-campaign-model']

- name: 'us-central1-docker.pkg.dev/umlops/gcr-umlops/bank-campaign-model'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/Lavalla-GH/gcp-airflow-cicd.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gcp-airflow-cicd/bank_campaign_model_training.py', 'gs://bumlops/dags']

images:
- 'us-central1-docker.pkg.dev/umlops/gcr-umlops/bank-campaign-model'

options:
  logging: CLOUD_LOGGING_ONLY